### ISSUE TITLE
Documentation: TFS Hook

### ISSUE THREAD

**Issue by gavinr** [rickduggan/TFSSlackRelay#10]
How do you get TFS to send a request to the '/incoming-webhook' endpoint? I don't see the code that is taking care of that, so I assume it's a configuration setting you have setup on your TFS server?

**Comment by rickduggan** [comment]
Yes, it's a configuration setting in TFS. Specifically, under Settings, there is tab called Service Hooks. Create a Service Hook that calls the /incoming-webhook endpoint.

Please let me know if you have any additional questions.

**Comment by gavinr** [comment]
I see it now. This feature: https://www.visualstudio.com/en-us/news/tfs2015-vs.aspx#svchook

My project does not have version 2015 yet - so that's why I didn't see it. Thanks for the feedback!
